import "../globals.css";

export const metadata = {
  title: "Marketing Layout",
  description: "Generated by create next app",
};

const marketingLayout = ({ children }) => {
  return (
    <html>
      <body>
        <p className="ml-5">marketingLayout</p>
        {children}
      </body>
    </html>
  );
};

export default marketingLayout;
